/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32f103x6.h"
#include "Stm32f103c6_GPIO_Driver.h"


void clock_init()
{
	RCC->APB2ENR |= (1<<2);

	RCC->APB2ENR |= (1<<3);
}

void GPIO_init()
{
	GPIO_PinConfig_t PinCfg;

	//PA1 input High-z floating input
	PinCfg.GPIO_pinNumber = GPIO_PIN1;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA , &PinCfg );

	//PB1 output push-pull
	PinCfg.GPIO_pinNumber = GPIO_PIN1;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB , &PinCfg );

	//PA13 input High-z floating input
	PinCfg.GPIO_pinNumber = GPIO_PIN13;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA , &PinCfg );

	//PB13 output push-pull
	PinCfg.GPIO_pinNumber = GPIO_PIN13;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB , &PinCfg );

}

void wait(int x)
{
	int i,j;
	for(i=0;i<x;i++)
	{
		for(j=0;j<255;j++);
	}
}


int main(void)
{
	clock_init();
	GPIO_init();

	/* Loop forever */
	while(1)
	{
		//Pin A1 connected to PUR
		if( MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN1) == 0)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN1);
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN1) == 0); //single press
		}

		//Pin A13 connected to PDR
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN13) == 1)
		{
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN13);
		}

		wait(1);
	}

}
