/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint_32;
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

//GPIOA
#define GPIOA_BASE 0x40010800
#define GPIOA_CRL *((vuint_32 *)(GPIOA_BASE + 0x00))
#define GPIOA_CRH *((vuint_32 *)(GPIOA_BASE + 0x04))
#define GPIOA_IDR *((vuint_32 *)(GPIOA_BASE + 0x08))
#define GPIOA_ODR *((vuint_32 *)(GPIOA_BASE + 0x0C))


//GPIOB
#define GPIOB_BASE 0x40010C00
#define GPIOB_CRL *((vuint_32 *)(GPIOB_BASE + 0x00))
#define GPIOB_CRH *((vuint_32 *)(GPIOB_BASE + 0x04))
#define GPIOB_ODR *((vuint_32 *)(GPIOB_BASE + 0x0C))
#define GPIOB_IDR *((vuint_32 *)(GPIOB_BASE + 0x08))


//RCC
#define RCC_BASE 0x40021000
#define RCC_APB2ENR  *((vuint_32 *)(RCC_BASE + 0x18))

void clock_init()
{
	/* Enable GPIOA clock */
		RCC_APB2ENR |= 1<<2 ;

	/* Enable GPIOB clock */
		RCC_APB2ENR |= 1<<3 ;
}


void GPIO_init()
{
	//GPIOA_CRL = 0x0;
	//GPIOB_CRL = 0x0;

	//pin1 PORTA input (HI-Z)
	GPIOA_CRL |= (1<<6);

	//pin13 PORTA input (HI-Z)
	GPIOA_CRH |= (1<<22);

	//pin1 PORTB output (push-pull)
	GPIOB_CRL &= ~(0b11<<6);
	GPIOB_CRL |= (0b01<<4);

	//pin13 PORTB output (push-pull)
	GPIOB_CRH &= ~(0b11<<22);
	GPIOB_CRH |= (0b01<<20);
}

void wait(int x)
{
	int i,j;
	for(i=0;i<x;i++)
	{
		for(j=0;j<255;j++);
	}
}

int main(void)
{
	clock_init();
	GPIO_init();

    /* Loop forever */
	while(1)
	{
		//Pin A1 connected to PUR
		if(( (GPIOA_IDR>>1) & 1 ) == 0)
		{
			GPIOB_ODR ^=(1<<1);
			while(( (GPIOA_IDR>>1) & 1 ) == 0); //single press
		}

		//Pin A13 connected to PDR
		if(( (GPIOA_IDR>>13) & 1 ) == 1)
		{
			GPIOB_ODR ^=(1<<13);
			//while(( (GPIOA_IDR>>1) & 1 ) == 0); //single press
		}

		wait(1);
	}

}
