/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32f103x6.h"
#include "Stm32f103c6_GPIO_Driver.h"
#include "Stm32f103c6_EXTI_Driver.h"
#include "LCD.h"
#include "Key_pad.h"

unsigned char IRQ_FLAG = 0;

void clock_init()
{

	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

void EXTI_PB9_call_back(void)
{

	IRQ_FLAG = 1;
	LCD_Write_string("IRQ EXTI9");
	_delay_ms(400);
}

int main(void)
{
	clock_init();
	LCD_init();

	EXTI_PinConfig_t EXTI_PIN;

	//Enable EXTI for PB9
	EXTI_PIN.EXTI_Pin = EXTI_PB9 ;
	EXTI_PIN.Trigger_case = EXTI_TRIGGER_Falling;
	EXTI_PIN.P_IRQ_Call_Back = EXTI_PB9_call_back;
	EXTI_PIN.EXTI_EN = EXTI_IRQ_Enable;
	MCAL_EXTI_GPIO_Init(&EXTI_PIN);


	IRQ_FLAG = 1;

	while(1)
	{
		if(IRQ_FLAG)
		{
		LCD_clear_screen();
		IRQ_FLAG = 0;
		}

	}

}

