/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32f103x6.h"
#include "Stm32f103c6_GPIO_Driver.h"
#include "LCD.h"
#include "Key_pad.h"

//Seven segment numbers
#define Zero 0x01
#define One  0x79
#define Two  0x24
#define Three 0x30
#define Four  0x58
#define Five 0x12
#define Six  0x02
#define Seven 0x19
#define Eight  0x00
#define Nine 0x10


void clock_init()
{
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}

void Seven_segment_init()
{
	GPIO_PinConfig_t PinCfg;

	PinCfg.GPIO_pinNumber = GPIO_PIN9;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB , &PinCfg );

	PinCfg.GPIO_pinNumber = GPIO_PIN10;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB , &PinCfg );

	PinCfg.GPIO_pinNumber = GPIO_PIN11;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg );

	PinCfg.GPIO_pinNumber = GPIO_PIN12;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB , &PinCfg );

	PinCfg.GPIO_pinNumber = GPIO_PIN13;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB , &PinCfg );

	PinCfg.GPIO_pinNumber = GPIO_PIN14;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB , &PinCfg );

	PinCfg.GPIO_pinNumber = GPIO_PIN15;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_OUTPUT_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB , &PinCfg );
}

void Seven_segment_display()
{
	int i;
	LCD_Write_string("Please Wait...");

	uint32_t Numbers[11]={Zero , One , Two , Three , Four , Five , Six , Seven , Eight , Nine , Zero};

	for(i=0 ; i<11 ; i++)
	{
		MCAL_GPIO_WritePort(GPIOB, Numbers[i]<<9);
		_delay_ms(200);
	}
	LCD_clear_screen();
	LCD_Write_string("Ready Now");
	LCD_clear_screen();
}

int main(void)
{
	clock_init();
	LCD_init();
	Seven_segment_init();

	_delay_ms(10);

	LCD_Write_string("Hello there");
	_delay_ms(400);
	LCD_clear_screen();

	Seven_segment_display();
	Key_pad_init();

	unsigned char pressed_key;
	while(1)
	{

		pressed_key = Key_pad_get_char();

		switch(pressed_key)
		{
		case '!':
			LCD_clear_screen();
			break;

		case 'N':
			break;

		default:
			LCD_Write_char(pressed_key);
		}

	}

}
